#!/bin/bash
# =============================================================================
# Slurm History Ingestor - Setup Script (Linux/Mac)
# =============================================================================
# This script will:
#   1. Prompt for database and Slurm configuration
#   2. Generate a .env file
#   3. Optionally run database migrations (all 3 migration files)
#   4. Install dependencies and build the binary
#   5. Optionally set up systemd service
# =============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_header() {
    echo ""
    echo -e "${BLUE}============================================${NC}"
    echo -e "${BLUE}  Slurm History Ingestor - Setup${NC}"
    echo -e "${BLUE}============================================${NC}"
    echo ""
}

print_step() {
    echo -e "${GREEN}[✓]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[!]${NC} $1"
}

print_error() {
    echo -e "${RED}[✗]${NC} $1"
}

# Check prerequisites
check_prerequisites() {
    echo -e "${BLUE}Checking prerequisites...${NC}"
    
    # Check Go
    if ! command -v go &> /dev/null; then
        print_error "Go is not installed. Please install Go 1.22+ first."
        echo "  Visit: https://go.dev/doc/install"
        exit 1
    fi
    
    GO_VERSION=$(go version | grep -oP 'go\d+\.\d+' | head -1)
    print_step "Go found: $GO_VERSION"
    
    # Check psql (optional, for migrations)
    if command -v psql &> /dev/null; then
        print_step "psql found (database migrations available)"
        PSQL_AVAILABLE=true
    else
        print_warning "psql not found. Database migrations will need to be run manually."
        PSQL_AVAILABLE=false
    fi
    
    echo ""
}

# Prompt for configuration
configure_environment() {
    echo -e "${BLUE}Configuration Mode${NC}"
    echo "------------------------"
    echo "Choose your ingest mode:"
    echo "  1) sacct (recommended - uses sacct command directly)"
    echo "  2) api (uses Slurm REST API)"
    read -p "Select mode [1]: " MODE_CHOICE
    MODE_CHOICE=${MODE_CHOICE:-1}
    
    echo ""
    echo -e "${BLUE}Database Configuration${NC}"
    echo "------------------------"
    
    read -p "Database Host [localhost]: " DB_HOST
    DB_HOST=${DB_HOST:-localhost}
    
    read -p "Database Port [5432]: " DB_PORT
    DB_PORT=${DB_PORT:-5432}
    
    read -p "Database Name [slurm_history]: " DB_NAME
    DB_NAME=${DB_NAME:-slurm_history}
    
    read -p "Database Username [slurm_user]: " DB_USER
    DB_USER=${DB_USER:-slurm_user}
    
    read -sp "Database Password: " DB_PASSWORD
    echo ""
    
    if [ -z "$DB_PASSWORD" ]; then
        print_warning "No password provided. Using empty password."
    fi
    
    read -p "SSL Mode [disable]: " DB_SSLMODE
    DB_SSLMODE=${DB_SSLMODE:-disable}
    
    if [ "$MODE_CHOICE" = "2" ]; then
        echo ""
        echo -e "${BLUE}Slurm API Configuration${NC}"
        echo "------------------------"
        
        read -p "Slurm Server URL [http://localhost:6820]: " SLURM_SERVER
        SLURM_SERVER=${SLURM_SERVER:-http://localhost:6820}
        
        read -p "Slurm API Account [slurm]: " SLURM_API_ACCOUNT
        SLURM_API_ACCOUNT=${SLURM_API_ACCOUNT:-slurm}
        
        read -sp "Slurm API Token: " SLURM_API_TOKEN
        echo ""
        
        read -p "Slurm API Version [v0.0.41]: " SLURM_API_VERSION
        SLURM_API_VERSION=${SLURM_API_VERSION:-v0.0.41}
    else
        echo ""
        echo -e "${BLUE}Sacct Configuration${NC}"
        echo "------------------------"
        
        read -p "Path to sacct binary [sacct]: " SACCT_PATH
        SACCT_PATH=${SACCT_PATH:-sacct}
    fi
    
    echo ""
    echo -e "${BLUE}Cluster Configuration${NC}"
    echo "------------------------"
    
    read -p "Cluster Name [mycluster]: " CLUSTER_NAME
    CLUSTER_NAME=${CLUSTER_NAME:-mycluster}
    
    read -p "Sync Interval in seconds [300]: " SYNC_INTERVAL
    SYNC_INTERVAL=${SYNC_INTERVAL:-300}
    
    read -p "Initial Sync Date (YYYY-MM-DD) [2024-01-01]: " INITIAL_SYNC_DATE
    INITIAL_SYNC_DATE=${INITIAL_SYNC_DATE:-2024-01-01}
    
    read -p "Enable Debug Mode? (y/n) [n]: " DEBUG_ENABLED
    if [[ "$DEBUG_ENABLED" =~ ^[Yy]$ ]]; then
        DEBUG=true
    else
        DEBUG=false
    fi
    
    echo ""
}

# Generate .env file
generate_env_file() {
    echo -e "${BLUE}Generating .env file...${NC}"
    
    DATABASE_URL="postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE}"
    
    cat > .env << EOF
# Generated by setup.sh on $(date)
# Slurm History Ingestor Configuration

# Database
DATABASE_URL=${DATABASE_URL}

# Cluster
CLUSTER_NAME=${CLUSTER_NAME}
SYNC_INTERVAL=${SYNC_INTERVAL}
INITIAL_SYNC_DATE=${INITIAL_SYNC_DATE}
DEBUG=${DEBUG}

EOF

    if [ "$MODE_CHOICE" = "2" ]; then
        cat >> .env << EOF
# Ingest Mode: API
INGEST_MODE=api
SLURM_SERVER=${SLURM_SERVER}
SLURM_API_ACCOUNT=${SLURM_API_ACCOUNT}
SLURM_API_TOKEN=${SLURM_API_TOKEN}
SLURM_API_VERSION=${SLURM_API_VERSION}
EOF
    else
        cat >> .env << EOF
# Ingest Mode: Sacct (recommended)
INGEST_MODE=sacct
SACCT_PATH=${SACCT_PATH}
EOF
    fi
    
    chmod 600 .env
    print_step ".env file created (permissions: 600)"
}

# Run database migrations
run_migrations() {
    if [ "$PSQL_AVAILABLE" = true ]; then
        echo ""
        read -p "Run database migrations now? (y/n) [y]: " RUN_MIGRATIONS
        RUN_MIGRATIONS=${RUN_MIGRATIONS:-y}
        
        if [[ "$RUN_MIGRATIONS" =~ ^[Yy]$ ]]; then
            echo -e "${BLUE}Running database migrations...${NC}"
            
            # Check if database exists, create if not
            if ! PGPASSWORD="$DB_PASSWORD" psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -lqt 2>/dev/null | cut -d \| -f 1 | grep -qw "$DB_NAME"; then
                print_warning "Database '$DB_NAME' does not exist. Attempting to create..."
                PGPASSWORD="$DB_PASSWORD" createdb -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" "$DB_NAME" 2>/dev/null || {
                    print_warning "Could not create database. You may need to create it manually."
                }
            fi
            
            # Run all migrations
            MIGRATION_SUCCESS=true
            for migration in db/migrations/001_init.sql db/migrations/002_add_gpu_fields.sql db/migrations/003_add_gpu_metrics.sql; do
                if [ -f "$migration" ]; then
                    echo "  Running $(basename $migration)..."
                    PGPASSWORD="$DB_PASSWORD" psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -f "$migration" 2>/dev/null || {
                        print_warning "Migration $(basename $migration) may have failed or tables already exist."
                        MIGRATION_SUCCESS=false
                    }
                else
                    print_warning "Migration file $migration not found"
                    MIGRATION_SUCCESS=false
                fi
            done
            
            if [ "$MIGRATION_SUCCESS" = true ]; then
                print_step "All database migrations completed"
            else
                print_warning "Some migrations had issues. Check manually if needed."
            fi
        else
            print_warning "Skipping migrations. Run manually with:"
            echo "  psql -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_NAME -f db/migrations/001_init.sql"
            echo "  psql -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_NAME -f db/migrations/002_add_gpu_fields.sql"
            echo "  psql -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_NAME -f db/migrations/003_add_gpu_metrics.sql"
        fi
    fi
}

# Install dependencies and build
build_application() {
    echo ""
    echo -e "${BLUE}Installing dependencies...${NC}"
    
    # Install sqlc
    echo "Installing sqlc..."
    go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
    print_step "sqlc installed"
    
    # Generate database code
    echo "Generating database code..."
    mkdir -p internal/db
    
    # Try to find sqlc in common locations
    if command -v sqlc &> /dev/null; then
        sqlc generate
    elif [ -f "$HOME/go/bin/sqlc" ]; then
        "$HOME/go/bin/sqlc" generate
    elif [ -f "$(go env GOPATH)/bin/sqlc" ]; then
        "$(go env GOPATH)/bin/sqlc" generate
    else
        print_error "sqlc not found in PATH. Please add \$GOPATH/bin to your PATH."
        exit 1
    fi
    print_step "Database code generated"
    
    # Tidy dependencies
    echo "Tidying Go modules..."
    go mod tidy
    print_step "Go modules tidied"
    
    # Build binary
    echo "Building binary..."
    go build -o slurm-ingestor cmd/ingest/main.go
    print_step "Binary built: ./slurm-ingestor"
}

# Setup systemd service
setup_systemd() {
    echo ""
    read -p "Set up systemd service? (requires sudo) (y/n) [n]: " SETUP_SYSTEMD
    
    if [[ "$SETUP_SYSTEMD" =~ ^[Yy]$ ]]; then
        echo -e "${BLUE}Setting up systemd service...${NC}"
        
        INSTALL_DIR="/opt/slurm-ingestor"
        
        # Create installation directory
        echo "Creating installation directory: $INSTALL_DIR"
        sudo mkdir -p "$INSTALL_DIR"
        
        # Copy files
        echo "Copying files..."
        sudo cp slurm-ingestor "$INSTALL_DIR/"
        sudo cp .env "$INSTALL_DIR/"
        sudo chmod +x "$INSTALL_DIR/slurm-ingestor"
        sudo chmod 600 "$INSTALL_DIR/.env"
        
        # Create systemd service file
        echo "Creating systemd service..."
        sudo tee /etc/systemd/system/slurm-ingestor.service > /dev/null << EOF
[Unit]
Description=Slurm History Ingestor
After=network.target remote-fs.target munge.service
Requires=remote-fs.target munge.service

[Service]
Type=simple
User=slurm
Group=slurm
WorkingDirectory=$INSTALL_DIR
ExecStart=$INSTALL_DIR/slurm-ingestor
Restart=on-failure
RestartSec=10
EnvironmentFile=$INSTALL_DIR/.env

[Install]
WantedBy=multi-user.target
EOF
        
        # Set ownership
        read -p "Run as user [slurm]: " SERVICE_USER
        SERVICE_USER=${SERVICE_USER:-slurm}
        read -p "Run as group [slurm]: " SERVICE_GROUP
        SERVICE_GROUP=${SERVICE_GROUP:-slurm}
        
        sudo chown -R "$SERVICE_USER:$SERVICE_GROUP" "$INSTALL_DIR"
        
        # Reload systemd
        sudo systemctl daemon-reload
        
        print_step "Systemd service created"
        echo ""
        echo "To start the service:"
        echo "  sudo systemctl enable --now slurm-ingestor"
        echo ""
        echo "To check status:"
        echo "  systemctl status slurm-ingestor"
        echo ""
        echo "To view logs:"
        echo "  journalctl -u slurm-ingestor -f"
    else
        print_warning "Skipping systemd setup"
    fi
}

# Print final instructions
print_instructions() {
    echo ""
    echo -e "${GREEN}============================================${NC}"
    echo -e "${GREEN}  Setup Complete!${NC}"
    echo -e "${GREEN}============================================${NC}"
    echo ""
    
    if [[ ! "$SETUP_SYSTEMD" =~ ^[Yy]$ ]]; then
        echo "To run the ingestor manually:"
        echo "  ./slurm-ingestor"
        echo ""
        echo "To run with Docker:"
        echo "  docker compose up -d"
        echo ""
        echo "To set up as a systemd service, re-run this script"
        echo "or see the documentation for manual setup."
    fi
    
    echo ""
}

# Main
main() {
    print_header
    check_prerequisites
    configure_environment
    generate_env_file
    run_migrations
    build_application
    setup_systemd
    print_instructions
}

main "$@"