#!/bin/bash
# =============================================================================
# Slurm History Ingestor - Setup Script (Linux/Mac)
# =============================================================================
# This script will:
#   1. Prompt for database and Slurm configuration
#   2. Generate a .env file
#   3. Optionally run database migrations
#   4. Install dependencies and build the binary
# =============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_header() {
    echo ""
    echo -e "${BLUE}============================================${NC}"
    echo -e "${BLUE}  Slurm History Ingestor - Setup${NC}"
    echo -e "${BLUE}============================================${NC}"
    echo ""
}

print_step() {
    echo -e "${GREEN}[✓]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[!]${NC} $1"
}

print_error() {
    echo -e "${RED}[✗]${NC} $1"
}

# Check prerequisites
check_prerequisites() {
    echo -e "${BLUE}Checking prerequisites...${NC}"
    
    # Check Go
    if ! command -v go &> /dev/null; then
        print_error "Go is not installed. Please install Go 1.22+ first."
        echo "  Visit: https://go.dev/doc/install"
        exit 1
    fi
    
    GO_VERSION=$(go version | grep -oP 'go\d+\.\d+' | head -1)
    print_step "Go found: $GO_VERSION"
    
    # Check psql (optional, for migrations)
    if command -v psql &> /dev/null; then
        print_step "psql found (database migrations available)"
        PSQL_AVAILABLE=true
    else
        print_warning "psql not found. Database migrations will need to be run manually."
        PSQL_AVAILABLE=false
    fi
    
    echo ""
}

# Prompt for configuration
configure_environment() {
    echo -e "${BLUE}Database Configuration${NC}"
    echo "------------------------"
    
    read -p "Database Host [localhost]: " DB_HOST
    DB_HOST=${DB_HOST:-localhost}
    
    read -p "Database Port [5432]: " DB_PORT
    DB_PORT=${DB_PORT:-5432}
    
    read -p "Database Name [slurm_history]: " DB_NAME
    DB_NAME=${DB_NAME:-slurm_history}
    
    read -p "Database Username [slurm_user]: " DB_USER
    DB_USER=${DB_USER:-slurm_user}
    
    read -sp "Database Password: " DB_PASSWORD
    echo ""
    
    if [ -z "$DB_PASSWORD" ]; then
        print_warning "No password provided. Using empty password."
    fi
    
    read -p "SSL Mode [disable]: " DB_SSLMODE
    DB_SSLMODE=${DB_SSLMODE:-disable}
    
    echo ""
    echo -e "${BLUE}Slurm API Configuration${NC}"
    echo "------------------------"
    
    read -p "Slurm Server URL [http://localhost:6820]: " SLURM_SERVER
    SLURM_SERVER=${SLURM_SERVER:-http://localhost:6820}
    
    read -p "Slurm API Account [slurm]: " SLURM_API_ACCOUNT
    SLURM_API_ACCOUNT=${SLURM_API_ACCOUNT:-slurm}
    
    read -sp "Slurm API Token: " SLURM_API_TOKEN
    echo ""
    
    read -p "Slurm API Version [v0.0.41]: " SLURM_API_VERSION
    SLURM_API_VERSION=${SLURM_API_VERSION:-v0.0.41}
    
    echo ""
    echo -e "${BLUE}Cluster Configuration${NC}"
    echo "------------------------"
    
    read -p "Cluster Name [mycluster]: " CLUSTER_NAME
    CLUSTER_NAME=${CLUSTER_NAME:-mycluster}
    
    read -p "Sync Interval in seconds [300]: " SYNC_INTERVAL
    SYNC_INTERVAL=${SYNC_INTERVAL:-300}
    
    read -p "Enable Debug Mode? (y/n) [n]: " DEBUG_ENABLED
    if [[ "$DEBUG_ENABLED" =~ ^[Yy]$ ]]; then
        DEBUG=true
    else
        DEBUG=false
    fi
    
    echo ""
}

# Generate .env file
generate_env_file() {
    echo -e "${BLUE}Generating .env file...${NC}"
    
    DATABASE_URL="postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE}"
    
    cat > .env << EOF
# Generated by setup.sh on $(date)
# Slurm History Ingestor Configuration

# Database
DATABASE_URL=${DATABASE_URL}

# Slurm API
SLURM_SERVER=${SLURM_SERVER}
SLURM_API_ACCOUNT=${SLURM_API_ACCOUNT}
SLURM_API_TOKEN=${SLURM_API_TOKEN}
SLURM_API_VERSION=${SLURM_API_VERSION}

# Cluster
CLUSTER_NAME=${CLUSTER_NAME}
SYNC_INTERVAL=${SYNC_INTERVAL}
DEBUG=${DEBUG}
EOF
    
    print_step ".env file created"
}

# Run database migrations
run_migrations() {
    if [ "$PSQL_AVAILABLE" = true ]; then
        echo ""
        read -p "Run database migrations now? (y/n) [y]: " RUN_MIGRATIONS
        RUN_MIGRATIONS=${RUN_MIGRATIONS:-y}
        
        if [[ "$RUN_MIGRATIONS" =~ ^[Yy]$ ]]; then
            echo -e "${BLUE}Running database migrations...${NC}"
            
            # Check if database exists, create if not
            if ! PGPASSWORD="$DB_PASSWORD" psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -lqt 2>/dev/null | cut -d \| -f 1 | grep -qw "$DB_NAME"; then
                print_warning "Database '$DB_NAME' does not exist. Attempting to create..."
                PGPASSWORD="$DB_PASSWORD" createdb -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" "$DB_NAME" 2>/dev/null || {
                    print_warning "Could not create database. You may need to create it manually."
                }
            fi
            
            # Run migrations
            PGPASSWORD="$DB_PASSWORD" psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -f db/migrations/001_init.sql 2>/dev/null && {
                print_step "Database migrations completed"
            } || {
                print_warning "Migration may have failed or tables already exist. Check manually if needed."
            }
        else
            print_warning "Skipping migrations. Run manually with:"
            echo "  psql -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_NAME -f db/migrations/001_init.sql"
        fi
    fi
}

# Install dependencies and build
build_application() {
    echo ""
    echo -e "${BLUE}Installing dependencies...${NC}"
    
    # Install sqlc
    echo "Installing sqlc..."
    go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
    print_step "sqlc installed"
    
    # Generate database code
    echo "Generating database code..."
    mkdir -p internal/db
    
    # Try to find sqlc in common locations
    if command -v sqlc &> /dev/null; then
        sqlc generate
    elif [ -f "$HOME/go/bin/sqlc" ]; then
        "$HOME/go/bin/sqlc" generate
    elif [ -f "$(go env GOPATH)/bin/sqlc" ]; then
        "$(go env GOPATH)/bin/sqlc" generate
    else
        print_error "sqlc not found in PATH. Please add \$GOPATH/bin to your PATH."
        exit 1
    fi
    print_step "Database code generated"
    
    # Tidy dependencies
    echo "Tidying Go modules..."
    go mod tidy
    print_step "Go modules tidied"
    
    # Build binary
    echo "Building binary..."
    go build -o slurm-ingestor cmd/ingest/main.go
    print_step "Binary built: ./slurm-ingestor"
}

# Print final instructions
print_instructions() {
    echo ""
    echo -e "${GREEN}============================================${NC}"
    echo -e "${GREEN}  Setup Complete!${NC}"
    echo -e "${GREEN}============================================${NC}"
    echo ""
    echo "To run the ingestor:"
    echo "  ./slurm-ingestor"
    echo ""
    echo "To run with Docker:"
    echo "  docker compose up -d"
    echo ""
    echo "To run as a systemd service, see DOCUMENTATION.md"
    echo ""
}

# Main
main() {
    print_header
    check_prerequisites
    configure_environment
    generate_env_file
    run_migrations
    build_application
    print_instructions
}

main "$@"
