// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID   int32
	Name string
}

type AccountMapping struct {
	AccountID      int32
	OrganizationID int32
}

type JobHistory struct {
	JobID            int64
	Cluster          string
	UserID           pgtype.Int4
	AccountID        pgtype.Int4
	Partition        pgtype.Text
	Qos              pgtype.Text
	JobState         string
	ExitCode         pgtype.Int4
	DerivedExitState pgtype.Text
	ReqCpus          pgtype.Int4
	ReqNodes         pgtype.Int4
	ReqMemMc         pgtype.Int8
	MaxRss           pgtype.Int8
	NodeList         pgtype.Text
	SubmitTime       pgtype.Timestamptz
	StartTime        pgtype.Timestamptz
	EndTime          pgtype.Timestamptz
	WaitTimeSeconds  pgtype.Int8
	RunTimeSeconds   pgtype.Int8
	CoreHours        float64 `json:"core_hours"`
	JobName          *string `json:"job_name"`
	TresAllocStr     *string `json:"tres_alloc_str"`
	TresReqStr       *string `json:"tres_req_str"`
	ArrayJobID       *int32  `json:"array_job_id"`
	ArrayTaskID      *int32  `json:"array_task_id"`
	GroupName        *string `json:"group_name"`
	EligibleTime     *int64  `json:"eligible_time"`
	TimelimitMinutes *int64  `json:"timelimit_minutes"`
}

type Organization struct {
	ID       int32
	Name     string
	Type     string
	ParentID pgtype.Int4
	Info     pgtype.Text
}

type User struct {
	ID   int32
	Name string
}
