// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BatchInsertHistoryParams struct {
	JobID            int64
	Cluster          string
	UserID           pgtype.Int4
	AccountID        pgtype.Int4
	Partition        pgtype.Text
	Qos              pgtype.Text
	JobState         string
	ExitCode         pgtype.Int4
	DerivedExitState pgtype.Text
	ReqCpus          pgtype.Int4
	ReqNodes         pgtype.Int4
	ReqMemMc         pgtype.Int8
	MaxRss           pgtype.Int8
	NodeList         pgtype.Text
	SubmitTime       pgtype.Timestamptz
	StartTime        pgtype.Timestamptz
	EndTime          pgtype.Timestamptz
	WaitTimeSeconds  pgtype.Int8
	RunTimeSeconds   pgtype.Int8
	CoreHours        pgtype.Numeric
	JobName          pgtype.Text
	TresAllocStr     pgtype.Text
	TresReqStr       pgtype.Text
	ArrayJobID       pgtype.Int4
	ArrayTaskID      pgtype.Int4
	GroupName        pgtype.Text
	EligibleTime     pgtype.Int8
	TimelimitMinutes pgtype.Int8
}

const getLastJobEndTime = `-- name: GetLastJobEndTime :one
SELECT MAX(end_time)::timestamptz FROM job_history WHERE cluster = $1
`

func (q *Queries) GetLastJobEndTime(ctx context.Context, cluster string) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLastJobEndTime, cluster)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const getOrCreateAccount = `-- name: GetOrCreateAccount :one
INSERT INTO accounts (name) VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id
`

func (q *Queries) GetOrCreateAccount(ctx context.Context, name string) (int32, error) {
	row := q.db.QueryRow(ctx, getOrCreateAccount, name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getOrCreateUser = `-- name: GetOrCreateUser :one
INSERT INTO users (name) VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id
`

func (q *Queries) GetOrCreateUser(ctx context.Context, name string) (int32, error) {
	row := q.db.QueryRow(ctx, getOrCreateUser, name)
	var id int32
	err := row.Scan(&id)
	return id, err
}
